"""premioResg

Revision ID: d36d8ca0c7c5
Revises: a34b7ea0ce64
Create Date: 2023-12-12 17:18:32.239721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36d8ca0c7c5'
down_revision = 'a34b7ea0ce64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('premio_resgatado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_doador', sa.Integer(), nullable=True),
    sa.Column('id_premio', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['id_doador'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['id_premio'], ['premio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('premio_resgatado')
    # ### end Alembic commands ###
