"""7

Revision ID: df3d1b2fa1d3
Revises: 
Create Date: 2023-11-20 07:49:40.116216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df3d1b2fa1d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=255), nullable=True),
    sa.Column('tipo_usuario', sa.String(length=64), nullable=True),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('nivel_acesso', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('premio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('descricao', sa.String(length=2000), nullable=True),
    sa.Column('pontos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.Column('id_tag', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['id_tag'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vinculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_doador', sa.Integer(), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.Column('pontos', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['id_doador'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_vinculo', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('descricao', sa.String(length=2000), nullable=True),
    sa.Column('pontos', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_vinculo'], ['vinculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('premio_resgatado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_doador', sa.Integer(), nullable=True),
    sa.Column('id_premio', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['id_doador'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['id_premio'], ['premio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('premio_resgatado')
    op.drop_table('entrega')
    op.drop_table('vinculo')
    op.drop_table('tag_empresa')
    op.drop_table('premio')
    op.drop_table('usuario')
    op.drop_table('tag')
    # ### end Alembic commands ###
